MACRO (add_compiler_flags)
  SET (CXX_STANDARD_REQUIRED ON)
  SET (CMAKE_CXX_STANDARD 14)
  SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  SET (CMAKE_CXX_OUTPUT_EXTENSION_REPLACE ON)
ENDMACRO ()

FUNCTION (sm_install target)
  INSTALL (
    TARGETS ${target}
    EXPORT AdasLibsTargets
    LIBRARY DESTINATION lib
    PUBLIC_HEADER DESTINATION include
    ARCHIVE DESTINATION lib
    RUNTIME DESTINATION bin
    INCLUDES
    DESTINATION include)

  INSTALL (
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/public/
    DESTINATION include
    FILES_MATCHING
    PATTERN "*.h*")

ENDFUNCTION ()
